name: Release

on:
  push:
    branches: [$default-branch]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read # for checkout

jobs:
  release:
    uses: sanity-io/.github/.github/workflows/changesets.yml@main
    permissions:
      contents: read # for checkout
      id-token: write # to enable use of OIDC for npm provenance
    # Uncomment if turborepo is setup, and secrets.TURBO_TOKEN is also set
    # with:
    #   TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    secrets: inherit
