name: Add changeset from conventional commits

on:
  workflow_call:
    secrets:
      ECOSPARK_APP_ID:
        required: true
      ECOSPARK_APP_PRIVATE_KEY:
        required: true

concurrency: ${{ github.repository_owner_id }}-${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  run:
    if: github.repository_owner == 'sanity-io'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.ECOSPARK_CLIENT_ID }}
          private-key: ${{ secrets.ECOSPARK_APP_PRIVATE_KEY }}
      - uses: mscharley/dependency-changesets-action@874dac2372a085cb94f750e8bdf5b1173a838a75 # v1.2.5
        with:
          token: ${{ steps.app-token.outputs.token }}
          use-conventional-commits: true
          sign-commits: true
